### PR TITLE
Keep registrants from brute-forcing SMS OTP verification

### PR DESCRIPTION
**Pull request by rjkip**

### CODE REVIEW

**Comment by rjkip** [comment]
@DRvanR :eyes: Similar to SS. Agree with 806e9d198f274e7eb513d658d104d8e706f7c3e3?

**Comment by DRvanR** [comment]
IIRC the max retries to be configurable was on request, so would consult SURF before removing that.

**Comment by DRvanR** [comment]
bar confirmation on the removal of the max retries, :+1:

**Comment by rjkip** [comment]
Removed removal of maximum OTP requests for maintenance sake (same code in SS).

**Pull request merged**
