### PR TITLE
Put cancel button left and send code button right.

### PR DESCRIPTION
**Pull request by relaxnow**
https://www.pivotaltracker.com/n/projects/1163646/stories/100299518

### CODE REVIEW

**Comment by relaxnow** [comment]
screen shot 2016-06-14 at 11 38 30

**Comment by rjkip** [comment]
The document shows the Cancel button directly to the left of the submit button

**Comment by relaxnow** [comment]
screen shot 2016-06-14 at 14 02 37

Damnit, you're right, I didn't see the screenshots in the document. Okay, fixed. @rjkip agree?

**Comment by rjkip** [comment]
:ship:

**Pull request merged**
